#include <openssl/des.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
struct Stats{uint64_t nodes=0,rejected_plaintext=0,maximum_depth=0;bool aborted=false;uint64_t rejected_weight=0,terminal_weight=0,rejected_strict=0;};
struct Solution{std::array<int,16>mapping;std::vector<unsigned char>suffix;};
static uint64_t fact[17];
static int hv(char c){if(c>='0'&&c<='9')return c-'0';if(c>='A'&&c<='F')return c-'A'+10;if(c>='a'&&c<='f')return c-'a'+10;throw std::runtime_error("bad hex");}
static std::string hex(const std::vector<unsigned char>&v){static const char*h="0123456789abcdef";std::string s;for(auto x:v){s+=h[x>>4];s+=h[x&15];}return s;}
static std::vector<unsigned char>unhex(const std::string&s){if(s.size()%2)throw std::runtime_error("odd hex");std::vector<unsigned char>v;for(size_t i=0;i<s.size();i+=2)v.push_back((hv(s[i])<<4)|hv(s[i+1]));return v;}
struct ECB{DES_key_schedule key{};mutable uint64_t calls=0;ECB(){DES_cblock k={'Z','o','m','b','i','e','s',0};DES_set_key_unchecked(&k,&key);}void encrypt(const unsigned char*in,unsigned char*out)const{calls++;DES_cblock a{},b{};memcpy(a,in,8);DES_ecb_encrypt(&a,&b,const_cast<DES_key_schedule*>(&key),DES_ENCRYPT);memcpy(out,b,8);}};
static bool relaxed(unsigned char v){return v==9||v==10||v==13||(v>=32&&v<=126)||v==0xe2||v==0x80||v==0x93||v==0x94||v==0x98||v==0x99||v==0xa6;}
static bool strict_suffix(const std::vector<unsigned char>&data){unsigned states=7;for(auto v:data){unsigned next=0;if(states&1){if(v==9||v==10||v==13||(v>=32&&v<=126))next|=1;else if(v==0xe2)next|=2;}if((states&2)&&v==0x80)next|=4;if((states&4)&&(v==0x93||v==0x94||v==0x98||v==0x99||v==0xa6))next|=1;states=next;if(!states)return false;}return states&1;}
struct Solver{
 ECB ecb;uint64_t cap;std::vector<std::pair<int,int>>pairs;std::vector<uint16_t>windows;std::array<int,16>mapping;uint16_t used=0;std::vector<int>order,todo;std::array<int,16>todo_index;std::vector<std::vector<int>>activate;std::vector<int>prebound;Stats st;std::vector<Solution>solutions;int seed_count=0,anchor_i=0,anchor_unique=0;bool order_override=false;std::vector<int>bound_counts;
 Solver(uint64_t c,const std::string&display,const std::string&seed,const std::string&explicit_order):cap(c){mapping.fill(-1);todo_index.fill(-1);if(display.size()%2)throw std::runtime_error("odd display");for(size_t i=0;i<display.size();i+=2)pairs.push_back({hv(display[i]),hv(display[i+1])});if(pairs.size()<=8)throw std::runtime_error("too short");for(size_t i=8;i<pairs.size();i++){uint16_t m=0;for(size_t j=i-8;j<=i;j++){m|=1u<<pairs[j].first;m|=1u<<pairs[j].second;}windows.push_back(m);}build_order();if(explicit_order!="-"&&!explicit_order.empty())apply_order(explicit_order);if(seed!="-"&&!seed.empty()){std::stringstream ss(seed);std::string q;while(std::getline(ss,q,',')){auto z=q.find(':');if(z==std::string::npos)throw std::runtime_error("bad seed");int a=std::stoi(q.substr(0,z)),b=std::stoi(q.substr(z+1));if(a<0||a>15||b<0||b>15||mapping[a]>=0||(used&(1u<<b)))throw std::runtime_error("bad seed");mapping[a]=b;used|=1u<<b;seed_count++;}}for(int s:order)if(mapping[s]<0){todo_index[s]=todo.size();todo.push_back(s);}activate.resize(todo.size());for(size_t wi=0;wi<windows.size();wi++){std::vector<int>pending;for(int s=0;s<16;s++)if((windows[wi]&(1u<<s))&&mapping[s]<0)pending.push_back(s);if(pending.empty())prebound.push_back(wi+8);else{int last=0;for(int s:pending)last=std::max(last,todo_index[s]);activate[last].push_back(wi+8);}}}
 void apply_order(const std::string&spec){if(spec.size()!=16)throw std::runtime_error("explicit order must be 16 hex symbols");uint16_t seen=0;std::vector<int>x;for(char c:spec){int s=hv(c);if(seen&(1u<<s))throw std::runtime_error("explicit order is not a bijection");seen|=1u<<s;x.push_back(s);}if(seen!=0xffff)throw std::runtime_error("explicit order is not a bijection");order=x;order_override=true;bound_counts.clear();uint16_t selected=0;for(int s:order){selected|=1u<<s;int bound=0;for(auto w:windows)if(!(w&~selected))bound++;bound_counts.push_back(bound);}}
 void build_order(){std::array<int,16>freq{};for(auto p:pairs){freq[p.first]++;freq[p.second]++;}int best_unique=17,best_cont=-1,best=-1;for(size_t i=0;i<windows.size();i++){int u=__builtin_popcount(windows[i]);int cont=0;for(auto w:windows)if(!(w&~windows[i]))cont++;if(u<best_unique||(u==best_unique&&(cont>best_cont||(cont==best_cont&&(int)i<best)))){best_unique=u;best_cont=cont;best=i;}}anchor_i=best+8;anchor_unique=best_unique;uint16_t selected=windows[best];std::vector<int>a;for(int s=0;s<16;s++)if(selected&(1u<<s))a.push_back(s);std::sort(a.begin(),a.end(),[&](int x,int y){return freq[x]!=freq[y]?freq[x]>freq[y]:x<y;});order=a;int bound=0;for(auto w:windows)if(!(w&~selected))bound++;bound_counts.push_back(bound);while(order.size()<16){int bs=-1,bnew=-1,bcontain=-1;for(int s=0;s<16;s++)if(!(selected&(1u<<s))){uint16_t after=selected|(1u<<s);int nb=0,contain=0;for(auto w:windows){if(!(w&~after)&&w&~selected)nb++;if(w&(1u<<s))contain++;}if(nb>bnew||(nb==bnew&&(contain>bcontain||(contain==bcontain&&(bs<0||s<bs))))){bs=s;bnew=nb;bcontain=contain;}}order.push_back(bs);selected|=1u<<bs;bound+=bnew;bound_counts.push_back(bound);}}
 unsigned char byte_at(int i)const{return (mapping[pairs[i].first]<<4)|mapping[pairs[i].second];}
 bool window_ok(int i)const{unsigned char reg[8],out[8];for(int j=0;j<8;j++)reg[j]=byte_at(i-8+j);ecb.encrypt(reg,out);return relaxed(byte_at(i)^out[0]);}
 std::vector<unsigned char>suffix()const{std::vector<unsigned char>o;for(size_t i=8;i<pairs.size();i++){unsigned char reg[8],out[8];for(int j=0;j<8;j++)reg[j]=byte_at(i-8+j);ecb.encrypt(reg,out);o.push_back(byte_at(i)^out[0]);}return o;}
 void rec(int depth){if(st.aborted)return;if(st.nodes>=cap){st.aborted=true;return;}st.nodes++;st.maximum_depth=std::max<uint64_t>(st.maximum_depth,seed_count+depth);if(depth==(int)todo.size()){auto s=suffix();if(strict_suffix(s)){st.terminal_weight++;solutions.push_back({mapping,s});}else{st.rejected_strict++;st.rejected_weight++;}return;}int symbol=todo[depth];for(int v=0;v<16;v++)if(!(used&(1u<<v))){mapping[symbol]=v;used|=1u<<v;bool ok=true;for(int i:activate[depth])if(!window_ok(i)){ok=false;break;}if(ok)rec(depth+1);else{st.rejected_plaintext++;st.rejected_weight+=fact[todo.size()-depth-1];}used^=1u<<v;mapping[symbol]=-1;if(st.aborted)break;}}
 void run(){bool ok=true;for(int i:prebound)if(!window_ok(i)){ok=false;break;}if(ok)rec(0);else{st.rejected_plaintext=1;st.rejected_weight=fact[todo.size()];}}
};
static void print_result(Solver&s,double sec){uint64_t expected=fact[s.todo.size()],cert=s.st.rejected_weight+s.st.terminal_weight;std::cout<<"{\"identity\":\"ASTRA\",\"cipher\":\"des\",\"node_limit\":"<<s.cap<<",\"seeded_entries\":"<<s.seed_count<<",\"expected_completion_weight\":"<<expected<<",\"certificate_weight\":"<<cert<<",\"certificate_complete\":"<<((!s.st.aborted&&cert==expected)?"true":"false")<<",\"unaccounted_mapping_weight\":"<<(expected-cert)<<",\"geometry\":{\"explicit_order_override\":"<<(s.order_override?"true":"false")<<",\"anchor_window_suffix_index\":"<<s.anchor_i<<",\"anchor_unique_symbols\":"<<s.anchor_unique<<",\"symbol_order\":[";for(size_t i=0;i<s.order.size();i++){if(i)std::cout<<",";std::cout<<s.order[i];}std::cout<<"],\"fully_bound_window_counts\":[";for(size_t i=0;i<s.bound_counts.size();i++){if(i)std::cout<<",";std::cout<<s.bound_counts[i];}std::cout<<"]},\"stats\":{\"nodes\":"<<s.st.nodes<<",\"rejected_plaintext\":"<<s.st.rejected_plaintext<<",\"maximum_depth\":"<<s.st.maximum_depth<<",\"aborted_at_node_limit\":"<<(s.st.aborted?"true":"false")<<",\"rejected_completion_weight\":"<<s.st.rejected_weight<<",\"terminal_completion_weight\":"<<s.st.terminal_weight<<",\"rejected_strict_fsa\":"<<s.st.rejected_strict<<"},\"ecb_calls\":"<<s.ecb.calls<<",\"elapsed_seconds\":"<<sec<<",\"solutions\":[";for(size_t i=0;i<s.solutions.size();i++){if(i)std::cout<<",";auto&q=s.solutions[i];std::cout<<"{\"mapping\":[";for(int j=0;j<16;j++){if(j)std::cout<<",";std::cout<<q.mapping[j];}std::cout<<"],\"plaintext_suffix_hex\":\""<<hex(q.suffix)<<"\"}";}std::cout<<"]}\n";}
int main(int argc,char**argv){try{fact[0]=1;for(int i=1;i<=16;i++)fact[i]=fact[i-1]*i;ECB e;if(argc==3&&std::string(argv[1])=="--block"){auto x=unhex(argv[2]);if(x.size()!=8)throw std::runtime_error("block size");unsigned char o[8];e.encrypt(x.data(),o);std::cout<<hex(std::vector<unsigned char>(o,o+8))<<"\n";return 0;}if(argc==3&&std::string(argv[1])=="--endpoint"){std::cout<<(strict_suffix(unhex(argv[2]))?"true":"false")<<"\n";return 0;}if(argc==4&&std::string(argv[1])=="--cfb-encrypt"){auto iv=unhex(argv[2]),x=unhex(argv[3]);if(iv.size()!=8)throw std::runtime_error("IV size");std::vector<unsigned char>o;for(auto v:x){unsigned char b[8];e.encrypt(iv.data(),b);unsigned char y=v^b[0];o.push_back(y);for(int i=1;i<8;i++)iv[i-1]=iv[i];iv[7]=y;}std::cout<<hex(o)<<"\n";return 0;}if(argc<3){std::cerr<<"usage: native CAP DISPLAY [SEED] [ORDER16HEX]\n";return 2;}auto begin=std::chrono::steady_clock::now();Solver s(std::stoull(argv[1]),argv[2],argc>3?argv[3]:"-",argc>4?argv[4]:"-");s.run();double sec=std::chrono::duration<double>(std::chrono::steady_clock::now()-begin).count();print_result(s,sec);return 0;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
